import {
  LayoutDashboard,
  BarChart3,
  Users,
  Package,
  ShoppingCart,
  FileText,
  BarChart,
  Settings,
  Bell,
} from 'lucide-react';
import { Module } from '@/types';

export const availableModules: Module[] = [
  {
    id: 'dashboard',
    name: 'Dashboard',
    description: 'Overview of key metrics and activities',
    icon: LayoutDashboard,
    route: '/dashboard',
    enabled: true,
    locked: true,
    category: 'core',
    features: [
      'Real-time metrics',
      'Activity feed',
      'Quick actions',
      'Performance charts',
    ],
  },
  {
    id: 'analytics',
    name: 'Analytics',
    description: 'Deep insights into your business performance',
    icon: BarChart3,
    route: '/dashboard/analytics',
    enabled: true,
    category: 'analytics',
    dependencies: ['dashboard'],
    features: [
      'Revenue tracking',
      'Traffic analytics',
      'Conversion metrics',
      'User behavior',
      'Real-time stats',
      'Custom reports',
    ],
  },
  {
    id: 'users',
    name: 'Users',
    description: 'Manage users, roles, and permissions',
    icon: Users,
    route: '/dashboard/users',
    enabled: true,
    category: 'core',
    features: [
      'User management',
      'Role-based access',
      'Activity logs',
      'Bulk operations',
      'Advanced filtering',
    ],
  },
  {
    id: 'products',
    name: 'Products',
    description: 'Manage your product catalog',
    icon: Package,
    route: '/dashboard/products',
    enabled: true,
    category: 'commerce',
    features: [
      'Product management',
      'Inventory tracking',
      'Categories & tags',
      'Variants',
      'Bulk import/export',
    ],
  },
  {
    id: 'orders',
    name: 'Orders',
    description: 'Track and manage orders',
    icon: ShoppingCart,
    route: '/dashboard/orders',
    enabled: true,
    category: 'commerce',
    dependencies: ['products'],
    features: [
      'Order processing',
      'Shipping management',
      'Invoice generation',
      'Refunds',
      'Order tracking',
    ],
  },
  {
    id: 'content',
    name: 'Content',
    description: 'Manage blog posts and media',
    icon: FileText,
    route: '/dashboard/content',
    enabled: true,
    category: 'content',
    features: [
      'Post management',
      'Rich text editor',
      'Media library',
      'SEO optimization',
      'Content calendar',
    ],
  },
  {
    id: 'reports',
    name: 'Reports',
    description: 'Generate and schedule reports',
    icon: BarChart,
    route: '/dashboard/reports',
    enabled: true,
    category: 'analytics',
    features: [
      'Custom reports',
      'Scheduled reports',
      'Export options',
      'Report templates',
    ],
  },
  {
    id: 'settings',
    name: 'Settings',
    description: 'Configure your application',
    icon: Settings,
    route: '/dashboard/settings',
    enabled: true,
    locked: true,
    category: 'settings',
    features: [
      'General settings',
      'Appearance',
      'Module configuration',
      'Integrations',
      'Security',
    ],
  },
  {
    id: 'notifications',
    name: 'Notifications',
    description: 'Manage notifications and alerts',
    icon: Bell,
    route: '/dashboard/notifications',
    enabled: true,
    category: 'communication',
    features: [
      'Notification center',
      'Email notifications',
      'Push notifications',
      'Notification preferences',
    ],
  },
];
